Repository rancher/ui, pull requests merged in 2018-12, with the labels that each got.

#2459 Fix markdown component issue
  lib/shared/addon/components/marked-down/component.js
Labels: status/ready-for-review

#2456 Support Aliyun/Tencent/Huawe hosted k8s
  .eslintrc.js
  app/authenticated/cluster/edit/route.js
  app/models/cluster.js
  app/styles/abstracts/_mixins.scss
  app/styles/pages/_host.scss
  ember-cli-build.js
  lib/nodes/addon/components/driver-aliyunecs/component.js
  lib/shared/addon/components/cluster-driver/driver-aliyunkcs/component.js
  lib/shared/addon/components/cluster-driver/driver-aliyunkcs/template.hbs
  lib/shared/addon/components/cluster-driver/driver-huaweicce/component.js
  lib/shared/addon/components/cluster-driver/driver-huaweicce/template.hbs
  lib/shared/addon/components/cluster-driver/driver-tencenttke/component.js
  lib/shared/addon/components/cluster-driver/driver-tencenttke/template.hbs
  lib/shared/addon/components/cru-cluster/component.js
  lib/shared/addon/components/huawei-user-labels/component.js
  lib/shared/addon/components/huawei-user-labels/template.hbs
  lib/shared/app/components/cluster-driver/driver-aliyunkcs/component.js
  lib/shared/app/components/cluster-driver/driver-huaweicce/component.js
  lib/shared/app/components/cluster-driver/driver-tencenttke/component.js
  lib/shared/app/components/huawei-user-labels/component.js
  public/assets/images/providers/aliyunkcs.svg
  public/assets/images/providers/huaweicce.svg
  public/assets/images/providers/tencenttke.svg
  translations/en-us.yaml
  translations/zh-hans.yaml
  vendor/aliyun-sdk.js
  vendor/cce-sdk.js
Labels: status/ready-for-merge

#2463 Fix graph area bug
  lib/shared/addon/components/metrics-summary/component.js
  lib/shared/addon/components/metrics-summary/template.hbs
Labels: status/ready-for-merge, status/ready-for-review

#2464 Upgrade Aliyun hosted k8s version
  lib/shared/addon/components/cluster-driver/driver-aliyunkcs/component.js
Labels: status/ready-for-merge, status/ready-for-review

#2465 Enable external server by default for Huawei hosted k8s
  lib/shared/addon/components/cluster-driver/driver-huaweicce/component.js
  lib/shared/addon/components/cluster-driver/driver-huaweicce/template.hbs
  translations/en-us.yaml
  translations/zh-hans.yaml
Labels: status/ready-for-merge, status/ready-for-review

#2468 Monitoring
  lib/shared/addon/components/graph-area/component.js
  lib/shared/addon/components/metrics-graph/component.js
  lib/shared/addon/components/metrics-graph/template.hbs
  lib/shared/addon/mixins/metrics.js
  translations/en-us.yaml
  translations/zh-hans.yaml
Labels: status/ready-for-merge, status/ready-for-review

#2473 Fix translation issues
  lib/monitoring/translations/en-us.yaml
  lib/monitoring/translations/zh-hans.yaml
  translations/en-us.yaml
Labels: status/ready-for-merge, status/ready-for-review

#2431 Route to cluster list if user doesn't have access to the cluster
  lib/shared/addon/mixins/preload.js
Labels: status/ready-for-review

#2492 Show images tooltip
  app/components/accordion-pod/template.hbs
  app/components/pod-row/template.hbs
  app/components/workload-row/template.hbs
  app/pod/template.hbs
  app/templates/tooltip-multi-lines.hbs
  lib/shared/addon/mixins/display-image.js
Labels: status/ready-for-review

#2519 Fix edit namespace cannot change project
  app/components/modal-edit-namespace/component.js
Labels: status/changes-requested

#2457 Catalog integration in Pipeline
  app/components/catalog-index/component.js
  lib/pipeline/addon/components/pipeline-steps/component.js
  lib/pipeline/addon/components/step-summary/template.hbs
  lib/pipeline/addon/components/steps/step-apply-catalog/component.js
  lib/pipeline/addon/components/steps/step-apply-catalog/template.hbs
  lib/pipeline/addon/components/steps/step-push-catalog/component.js
  lib/pipeline/addon/components/steps/step-push-catalog/template.hbs
  lib/pipeline/app/components/steps/step-apply-catalog/component.js
  lib/pipeline/app/components/steps/step-push-catalog/component.js
  lib/pipeline/translations/en-us.yaml
  lib/shared/addon/utils/pipeline-constants.js
  lib/shared/addon/utils/util.js
  lib/shared/app/utils/util.js
Labels: status/ready-for-review
