Repository rancher/ui, pull requests merged in 2018-11, with the labels that each got.

#2370 Add setting to whitelist redirect domains for auth
  app/components/settings/danger-zone/component.js
Labels: status/waiting-backend-changes

#2355 UI Support private catalog for auth
  app/models/catalog.js
  lib/shared/addon/components/custom-catalog/component.js
  lib/shared/addon/components/modal-edit-catalog/component.js
  lib/shared/addon/components/modal-edit-catalog/template.hbs
  translations/en-us.yaml
Labels: status/ready-for-merge

#2418 Configmap
  app/authenticated/project/config-maps/index/template.hbs
  app/components/cru-config-map/template.hbs
  lib/shared/addon/components/form-key-value/component.js
  lib/shared/addon/components/form-key-value/template.hbs
  lib/shared/addon/components/modal-yaml/template.hbs
  lib/shared/addon/mixins/upload.js
  lib/shared/app/mixins/upload.js
Labels: status/has-questions

#2353 UI support for pipeline notification config
  app/app.js
  lib/pipeline/addon/components/edit-pipeline-config/component.js
  lib/pipeline/addon/components/edit-pipeline-config/template.hbs
  lib/pipeline/addon/components/form-recipient-item/component.js
  lib/pipeline/addon/components/form-recipient-item/template.hbs
  lib/pipeline/addon/components/pipeline-notifier/component.js
  lib/pipeline/addon/components/pipeline-notifier/template.hbs
  lib/pipeline/addon/engine.js
  lib/pipeline/addon/pipelines/edit/route.js
  lib/pipeline/translations/en-us.yaml
  lib/pipeline/translations/zh-hans.yaml
  lib/shared/addon/utils/constants.js
Labels: status/waiting-backend-changes

#2421 Pluggable Cluster Driver UI
  app/instance-initializers/nav.js
  app/models/kontainerdriver.js
  app/styles/pages/_host.scss
  lib/global-admin/addon/clusters/new/route.js
  lib/global-admin/index.js
  lib/nodes/addon/custom-drivers/cluster-drivers/controller.js
  lib/nodes/addon/custom-drivers/cluster-drivers/route.js
  lib/nodes/addon/custom-drivers/cluster-drivers/template.hbs
  lib/nodes/addon/custom-drivers/index/route.js
  lib/nodes/addon/custom-drivers/node-drivers/controller.js
  lib/nodes/addon/custom-drivers/node-drivers/route.js
  lib/nodes/addon/custom-drivers/node-drivers/template.hbs
  lib/nodes/addon/custom-drivers/template.hbs
  lib/nodes/addon/routes.js
  lib/nodes/app/custom-drivers/cluster-drivers/controller.js
  lib/nodes/app/custom-drivers/cluster-drivers/route.js
  lib/nodes/app/custom-drivers/cluster-drivers/template.js
  lib/nodes/app/custom-drivers/index/route.js
  lib/nodes/app/custom-drivers/index/template.js
  lib/nodes/app/custom-drivers/route.js
  lib/nodes/app/custom-drivers/template.js
  lib/shared/addon/components/cru-cluster/component.js
  lib/shared/addon/components/cru-cluster/template.hbs
  lib/shared/addon/components/modal-edit-driver/component.js
  lib/shared/addon/components/modal-edit-driver/template.hbs
  translations/en-us.yaml
Labels: status/WIP, status/waiting-backend-changes
