Repository rancher/ui, pull requests merged in 2018-09, with the labels that each got.

#2208 Update resource quota
  app/authenticated/cluster/projects/new-ns/controller.js
  app/authenticated/cluster/projects/new-ns/template.hbs
  app/components/input-resource-quota/component.js
  app/components/input-resource-quota/template.hbs
  app/components/modal-edit-namespace/component.js
  app/components/modal-edit-namespace/template.hbs
  app/components/namespace-quota-row/component.js
  app/components/namespace-quota-row/template.hbs
  app/components/namespace-resource-quota/component.js
  app/components/namespace-resource-quota/template.hbs
  app/components/new-edit-project/component.js
  app/components/new-edit-project/template.hbs
  app/components/project-group/template.hbs
  app/components/project-quota-row/component.js
  app/components/project-quota-row/template.hbs
  app/components/project-resource-quota/component.js
  app/components/project-resource-quota/template.hbs
  app/components/resource-quota-row/template.hbs
  app/components/resource-quota-select/component.js
  app/components/resource-quota-select/template.hbs
  app/models/namespace.js
  lib/shared/addon/utils/constants.js
  translations/en-us.yaml
  translations/zh-hans.yaml
Labels: status/changes-requested

#2214 Support certificate type volume
  app/components/container/form-volume-row/template.hbs
  app/components/container/form-volumes/component.js
  app/components/container/form-volumes/template.hbs
  app/components/volume-source/source-certificate/component.js
  app/components/volume-source/source-certificate/template.hbs
  lib/shared/addon/components/schema/input-secret/component.js
  lib/shared/addon/components/schema/input-secret/template.hbs
  lib/shared/addon/utils/constants.js
  translations/en-us.yaml
Labels: status/changes-requested

#2178 Update created column style
  app/authenticated/apikeys/controller.js
  app/authenticated/project/config-maps/index/controller.js
  app/authenticated/project/ns/index/controller.js
  app/authenticated/project/ns/index/template.hbs
  app/authenticated/project/secrets/index/controller.js
  app/components/apikey-row/template.hbs
  app/components/config-map-row/template.hbs
  app/components/namespace-list/component.js
  app/components/namespace-list/template.hbs
  app/components/namespace-table/component.js
  app/components/namespace-table/template.hbs
  app/components/notifier/notifier-row/template.hbs
  app/components/notifier/notifier-table/component.js
  app/components/secret-row/template.hbs
  app/ingresses/index/controller.js
  app/ingresses/index/template.hbs
  lib/global-admin/addon/components/cluster-row/template.hbs
Labels: status/has-questions

#2250 Validate limits and requests if resource quota is enabled in project
  app/components/container/form-security/template.hbs
  app/components/container/new-edit/component.js
  app/components/container/new-edit/template.hbs
  app/models/container.js
  app/models/workload.js
Labels: status/changes-requested

#2254 Warning message in ports section for workload not created by Rancher
  app/components/container/form-ports/component.js
  app/components/container/form-ports/template.hbs
  app/components/container/new-edit/template.hbs
  app/models/workload.js
  lib/shared/addon/utils/constants.js
  translations/en-us.yaml
Labels: status/changes-requested

#2258 Fix log volume issue
  app/components/container/form-volume-row/template.hbs
  app/components/container/form-volumes/component.js
  app/components/container/form-volumes/template.hbs
  app/components/volume-source/source-custom-log-path/template.hbs
  app/container/template.hbs
  app/workload/template.hbs
Labels: status/changes-requested

#2251 Convert node name to lowercase in registration command
  lib/shared/addon/components/cluster-driver/driver-rke/component.js
  lib/shared/addon/utils/parse-label.js
  package.json
  translations/en-us.yaml
Labels: status/has-pr-dependency

#2272 Configurable notifiers parameters are confusing
  app/components/notifier/modal-new-edit/component.js
  app/components/notifier/modal-new-edit/template.hbs
  app/components/notifier/notifier-row/template.hbs
  app/mixins/model-alert.js
  app/mixins/notifier.js
  app/models/notifier.js
  lib/alert/addon/components/alert/form-recipient-item/template.hbs
  lib/alert/translations/en-us.yaml
  lib/shared/addon/utils/constants.js
  translations/en-us.yaml
Labels: status/changes-requested

#2284 Update hasOwner check logic
  lib/shared/addon/components/form-members/component.js
Labels: status/changes-requested
