Repository rancher/ui, pull requests merged in 2018-08, with the labels that each got.

#2134 Upgrade Ember 3.3 && Lazy Loading
  app/application/route.js
  app/components/page-header/component.js
  app/components/page-header/template.hbs
  app/components/project-table/template.hbs
  app/initializers/extend-ember-route.js
  app/mixins/model-alert.js
  app/mixins/notifier.js
  app/models/clusteralert.js
  app/models/pipeline.js
  app/models/pipelineexecution.js
  app/models/projectalert.js
  app/models/sourcecodecredential.js
  app/models/stagestatus.js
  app/not-found/route.js
  lib/alert/addon/components/alert/form-cluster-rules/component.js
  lib/alert/addon/components/alert/form-cluster-rules/template.hbs
  lib/alert/addon/components/cluster-alert-row/component.js
  lib/alert/addon/components/project-alert-row/component.js
  lib/alert/app/models/clusteralert.js
  lib/alert/app/models/projectalert.js
  lib/alert/index.js
  lib/global-admin/index.js
  lib/logging/index.js
  lib/login/index.js
  lib/pipeline/addon/components/input-image/component.js
  lib/pipeline/addon/components/modal-pipeline-new-step/component.js
  lib/pipeline/addon/components/pipeline-input-var-hint/component.js
  lib/pipeline/addon/components/pipeline-step-task/component.js
  lib/pipeline/addon/components/pipeline-step/component.js
  lib/pipeline/addon/components/step-scm/component.js
  lib/pipeline/addon/models/clusterpipeline.js
  lib/pipeline/app/helpers/pretty-cron.js
  lib/pipeline/app/models/clusterpipeline.js
  lib/pipeline/app/models/pipeline.js
  lib/pipeline/app/models/pipelineexecution.js
  lib/pipeline/app/models/sourcecodecredential.js
  lib/pipeline/app/models/stagestatus.js
  lib/pipeline/app/services/code-mirror.js
  lib/pipeline/app/services/pipeline-github.js
  lib/pipeline/app/services/pipeline.js
  lib/pipeline/app/utils/pipelineStep.js
  lib/pipeline/ember-cli-build.js
  lib/pipeline/index.js
  lib/shared/addon/code-mirror/service.js
  lib/shared/addon/components/banner-message/component.js
  lib/shared/addon/components/link-to-as-attrs/component.js
  lib/shared/addon/helpers/pretty-cron.js
  lib/shared/addon/pipeline-github/service.js
  lib/shared/addon/pipeline/service.js
  lib/shared/addon/utils/branchConditionsEnums.js
  lib/shared/addon/utils/navigation-tree.js
  lib/shared/addon/utils/pipelineStep.js
  lib/shared/app/code-mirror/service.js
  lib/shared/app/helpers/pretty-cron.js
  lib/shared/app/pipeline-github/service.js
  lib/shared/app/pipeline/service.js
  lib/shared/app/utils/branchConditionsEnums.js
  lib/shared/app/utils/pipelineStep.js
  package.json
  yarn.lock
Labels: status/WIP

#2144 Support bulk actions for pod list in workload detail page
  app/components/accordion-pod/template.hbs
Labels: status/waiting-backend-changes

#1900 Support edit yaml for catalog without questions
  app/components/input-answers/component.js
  app/components/input-answers/template.hbs
  app/components/input-custom-answers/component.js
  app/components/input-custom-answers/template.hbs
  app/components/new-catalog/component.js
  app/components/new-catalog/template.hbs
  lib/shared/package.json
  package.json
  translations/en-us.yaml
  translations/zh-hans.yaml
Labels: status/changes-requested

#2114 [WIP] Read Certificate SANs from list
  app/models/certificate.js
  translations/en-us.yaml
  translations/zh-hans.yaml
Labels: status/ready-for-review

#2182 Fix the issue that user can not deploy catalog item
  lib/shared/addon/catalog/service.js
  lib/shared/addon/components/schema/input-boolean/component.js
  lib/shared/addon/components/schema/input-enum/template.hbs
Labels: status/changes-requested

#2179 System project
  app/authenticated/cluster/route.js
  lib/shared/addon/components/confirm-delete/component.js
  lib/shared/addon/components/confirm-delete/template.hbs
  translations/en-us.yaml
Labels: status/changes-requested

#1945 Windows deploy supported
  app/styles/base/_color.scss
  lib/shared/addon/components/cluster-driver/driver-rke/component.js
  lib/shared/addon/components/cluster-driver/driver-rke/template.hbs
  lib/shared/addon/components/container-shell/component.js
  translations/en-us.yaml
Labels: status/changes-requested, status/waiting-backend-changes

#2174 Fix volume issue
  app/components/container/form-volume-row/component.js
  app/components/cru-persistent-volume/component.js
  app/components/cru-volume/component.js
  app/components/cru-volume/template.hbs
  app/components/volume-source/source-aws-ebs/component.js
  app/components/volume-source/source-aws-ebs/template.hbs
  app/components/volume-source/source-azure-disk/component.js
  app/components/volume-source/source-azure-disk/template.hbs
  app/components/volume-source/source-azure-file/component.js
  app/components/volume-source/source-azure-file/template.hbs
  app/components/volume-source/source-cephfs/component.js
  app/components/volume-source/source-cephfs/template.hbs
  app/components/volume-source/source-cinder/component.js
  app/components/volume-source/source-cinder/template.hbs
  app/components/volume-source/source-config-map/component.js
  app/components/volume-source/source-empty-dir/component.js
  app/components/volume-source/source-fc/component.js
  app/components/volume-source/source-fc/template.hbs
  app/components/volume-source/source-flex-volume-longhorn/component.js
  app/components/volume-source/source-flex-volume-longhorn/template.hbs
  app/components/volume-source/source-flex-volume/component.js
  app/components/volume-source/source-flex-volume/template.hbs
  app/components/volume-source/source-flocker/component.js
  app/components/volume-source/source-gce-pd/component.js
  app/components/volume-source/source-gce-pd/template.hbs
  app/components/volume-source/source-glusterfs/component.js
  app/components/volume-source/source-host-path/component.js
  app/components/volume-source/source-host-path/template.hbs
  app/components/volume-source/source-iscsi/component.js
  app/components/volume-source/source-iscsi/template.hbs
  app/components/volume-source/source-local/component.js
  app/components/volume-source/source-nfs/component.js
  app/components/volume-source/source-nfs/template.hbs
  app/components/volume-source/source-photon/component.js
  app/components/volume-source/source-photon/template.hbs
  app/components/volume-source/source-portworx/component.js
  app/components/volume-source/source-portworx/template.hbs
  app/components/volume-source/source-quobyte/component.js
  app/components/volume-source/source-quobyte/template.hbs
  app/components/volume-source/source-rbd/component.js
  app/components/volume-source/source-rbd/template.hbs
  app/components/volume-source/source-scaleio/component.js
  app/components/volume-source/source-scaleio/template.hbs
  app/components/volume-source/source-secret/component.js
  app/components/volume-source/source-storageos/component.js
  app/components/volume-source/source-storageos/template.hbs
  app/components/volume-source/source-vsphere-volume/component.js
  app/components/volume-source/source-vsphere-volume/template.hbs
  lib/shared/addon/mixins/volume-source.js
  translations/en-us.yaml
  translations/zh-hans.yaml
Labels: status/changes-requested

#2201 Fix node alert issue
  app/components/cluster-dashboard/component.js
  lib/shared/addon/utils/constants.js
Labels: status/changes-requested
