Repository rancher/ui, pull requests merged in 2019-01, with the labels that each got.

#2529 Support WeChat as notifier
  app/components/notifier/modal-new-edit/component.js
  app/components/notifier/modal-new-edit/template.hbs
  app/models/notifier.js
  app/styles/components/_nav-boxes.scss
  lib/shared/addon/utils/constants.js
  public/assets/images/providers/wechat.svg
  translations/en-us.yaml
Labels: status/ready-for-review

#2542 Fix form-key-to-path bug
  app/components/form-key-to-path/component.js
Labels: status/changes-requested

#2539 button fixes for 16924
  app/components/page-header-project/template.hbs
  app/styles/components/_button.scss
  app/styles/components/_page-header.scss
  app/styles/layout/_header.scss
  yarn.lock
Labels: status/changes-requested

#2559 general ui polish
  app/components/page-header-project/template.hbs
  app/models/nodedriver.js
  app/styles/abstracts/_mixins.scss
  app/styles/layout/_medium.scss
  app/styles/pages/_host.scss
  lib/global-admin/addon/components/cluster-row/template.hbs
  lib/nodes/addon/components/modal-edit-node-template/template.hbs
  lib/shared/addon/components/cru-cluster/template.hbs
  lib/shared/addon/components/settings/danger-zone/template.hbs
  public/assets/images/providers/aliyunecs.svg
  public/assets/images/providers/open-telekom-cloud.svg
  public/assets/images/providers/openstack.svg
  public/assets/images/providers/packet.svg
  public/assets/images/providers/rackspace.svg
  translations/en-us.yaml
Labels: status/ready-for-review

#2538 Logging feature && bug
  app/components/volume-source/source-custom-log-path/component.js
  app/mixins/logging-model.js
  app/styles/layout/_layout.scss
  lib/logging/addon/components/logging/form-log-format/template.hbs
  lib/logging/addon/components/logging/form-log-ssl/component.js
  lib/logging/addon/components/logging/form-log-ssl/template.hbs
  lib/logging/addon/components/logging/form-test/component.js
  lib/logging/addon/components/logging/form-test/template.hbs
  lib/logging/addon/components/logging/input-logging-config/component.js
  lib/logging/addon/components/logging/input-logging-config/template.hbs
  lib/logging/addon/components/logging/new-edit/component.js
  lib/logging/addon/components/logging/new-edit/template.hbs
  lib/logging/addon/components/logging/target-elasticsearch/component.js
  lib/logging/addon/components/logging/target-elasticsearch/template.hbs
  lib/logging/addon/components/logging/target-kafka/component.js
  lib/logging/addon/components/logging/target-kafka/template.hbs
  lib/logging/addon/components/logging/target-splunk/component.js
  lib/logging/addon/components/logging/target-splunk/template.hbs
  lib/logging/addon/components/logging/target-syslog/component.js
  lib/logging/addon/components/logging/target-syslog/template.hbs
  lib/logging/translations/en-us.yaml
  lib/logging/translations/zh-hans.yaml
  lib/shared/addon/components/input-text-file/component.js
  lib/shared/addon/components/input-text-file/template.hbs
  lib/shared/addon/components/textarea-autogrow/component.js
  lib/shared/addon/utils/constants.js
Labels: status/changes-requested

#2573 Support more alert group config
  lib/alert/addon/components/alert-rule/new-edit/template.hbs
  lib/alert/addon/components/alert/form-advanced/component.js
  lib/alert/addon/components/alert/form-advanced/template.hbs
  lib/alert/addon/components/alert/new-edit/template.hbs
Labels: status/changes-requested

#2574 Fix clone cluster alert rule throw an error
  lib/alert/addon/edit-rule/route.js
  lib/alert/addon/mixins/edit-or-clone.js
  lib/alert/addon/new-rule/route.js
Labels: status/changes-requested

#2568 Update EKS regions and add k8s version
  lib/shared/addon/components/cluster-driver/driver-amazoneks/component.js
  lib/shared/addon/components/cluster-driver/driver-amazoneks/template.hbs
  lib/shared/addon/components/form-versions/component.js
  lib/shared/addon/utils/parse-version.js
  translations/en-us.yaml
  translations/zh-hans.yaml
Labels: status/changes-requested

#2572 Add current scale in Workload view
  app/models/workload.js
  app/styles/base/_helpers.scss
  app/styles/components/_banners.scss
  app/workload/template.hbs
  translations/en-us.yaml
  translations/zh-hans.yaml
Labels: status/changes-requested

#2580 Expose authorized cluster endpoint on rke clusters
  app/authenticated/apikeys/controller.js
  app/components/apikey-row/template.hbs
  app/components/modal-edit-apikey/component.js
  app/components/modal-edit-apikey/template.hbs
  lib/shared/addon/components/authorized-endpoint/component.js
  lib/shared/addon/components/authorized-endpoint/template.hbs
  lib/shared/addon/components/cluster-driver/driver-rke/component.js
  lib/shared/addon/components/cluster-driver/driver-rke/template.hbs
  lib/shared/app/components/authorized-endpoint/component.js
  translations/en-us.yaml
Labels: status/ready-for-review

#2585 Use array for ingress rule path
  lib/shared/addon/components/form-ingress-backends/component.js
Labels: status/ready-for-review, status/waiting-backend-changes

#2592 Support Kafka sasl/scram-256
  lib/logging/addon/components/logging/form-log-ssl/template.hbs
  lib/logging/addon/components/logging/new-edit/component.js
  lib/logging/addon/components/logging/target-kafka/component.js
  lib/logging/addon/components/logging/target-kafka/template.hbs
  lib/logging/translations/en-us.yaml
  lib/logging/translations/zh-hans.yaml
Labels: status/changes-requested
