Repository rancher/ui, pull requests merged in 2019-02, with the labels that each got.

#2611 Add new field for AKS
  lib/shared/addon/components/cluster-driver/driver-azureaks/component.js
  lib/shared/addon/components/cluster-driver/driver-azureaks/template.hbs
  translations/en-us.yaml
  translations/zh-hans.yaml
Labels: hold-for-next-release

#2615 Support request and limit for pipeline executor
  lib/pipeline/addon/components/settings-git/component.js
  lib/pipeline/addon/components/settings-git/template.hbs
  lib/pipeline/translations/en-us.yaml
Labels: hold-for-next-release

#2616 minor ui polish
  app/styles/components/_forms.scss
  app/styles/themes/_dark.scss
  public/assets/images/providers/generic-driver.svg
  public/assets/images/providers/old-route53.svg
Labels: hold-for-next-release

#2623 Fix aws node template issue
  lib/nodes/addon/components/driver-amazonec2/component.js
Labels: hold-for-next-release

#2627 EKS form-version align issue
  lib/shared/addon/components/cluster-driver/driver-amazoneks/component.js
  lib/shared/addon/components/cluster-driver/driver-amazoneks/template.hbs
  lib/shared/addon/components/new-select/component.js
  translations/en-us.yaml
Labels: hold-for-next-release

#2630 button alignment
  app/styles/components/_button.scss
Labels: status/ready-for-review

#2541 Add GKE fields
  lib/shared/addon/components/cluster-driver/driver-googlegke/component.js
  lib/shared/addon/components/cluster-driver/driver-googlegke/template.hbs
  lib/shared/addon/components/form-gke-taints/component.js
  lib/shared/addon/components/form-gke-taints/template.hbs
  lib/shared/addon/components/form-value-array/template.hbs
  lib/shared/addon/components/gke-access-scope/component.js
  lib/shared/addon/components/gke-access-scope/template.hbs
  lib/shared/addon/components/searchable-select/component.js
  lib/shared/app/components/form-gke-taints/component.js
  lib/shared/app/components/gke-access-scope/component.js
  translations/en-us.yaml
  translations/zh-hans.yaml
Labels: status/changes-requested

#2674 add state badge to etcd backups page
  app/authenticated/cluster/backups/controller.js
  app/authenticated/cluster/backups/template.hbs
Labels: status/waiting-backend-changes

#2654 Show API response in embedded kubectl view
  lib/shared/addon/components/container-shell/component.js
  lib/shared/addon/components/container-shell/template.hbs
  translations/en-us.yaml
  translations/zh-hans.yaml
Labels: status/changes-requested
