Repository rancher/ui, pull requests merged in 2020-05, with the labels that each got.

#3926 [2.4.x] Fix log volume format button issue
  app/components/volume-source/source-custom-log-path/template.hbs
Labels: status/ready-for-review

#3927 [Master] Fix log volume format button issue
  app/components/volume-source/source-custom-log-path/template.hbs
Labels: status/ready-for-review

#3932 [Master] Fix node name display issue
  app/components/container/form-scheduling/component.js
  app/models/node.js
Labels: status/ready-for-review

#3933 [2.4] Fix node name display issue
  app/components/container/form-scheduling/component.js
  app/models/node.js
Labels: status/ready-for-review

#3951 Fix dockerVersion display issue
  lib/monitoring/addon/components/system-info-section/component.js
  translations/en-us.yaml
  translations/zh-hans.yaml
Labels: status/ready-for-review

#3981 [2.4.4] Hide Windows logging warning in k8s 1.18
  lib/logging/addon/components/logging/new-edit/component.js
  lib/logging/addon/components/logging/new-edit/template.hbs
Labels: status/ready-for-merge

#3982 [Master] Hide Windows logging warning in k8s 1.18
  lib/logging/addon/components/logging/new-edit/component.js
  lib/logging/addon/components/logging/new-edit/template.hbs
Labels: status/ready-for-merge

#3994 [backport 2.3] Fix registry credentials so that it doesn't crash
  app/components/cru-registry/component.js
Labels: status/ready-for-review

#3973 [2.4] Azure Node Template Expose NSG
  lib/nodes/addon/components/driver-azure/component.js
  lib/nodes/addon/components/driver-azure/template.hbs
  translations/en-us.yaml
Labels: status/has-pr-dependency

#3972 Azure Node Template Expose NSG
  lib/nodes/addon/components/driver-azure/component.js
  lib/nodes/addon/components/driver-azure/template.hbs
  translations/en-us.yaml
Labels: status/has-pr-dependency

#3996 [Master] Fix mobile cluster dropdown issue
  app/styles/layout/_medium.scss
  server/proxies/api.js
Labels: status/ready-for-review

#3995 [2.4.4] Fix cluster dropdown style issue on mobile
  app/styles/layout/_medium.scss
  server/proxies/api.js
Labels: status/ready-for-review

#4001 [Master] Add k8s version options for TKE
  lib/shared/addon/components/cluster-driver/driver-tencenttke/component.js
Labels: status/ready-for-review

#4002 [2.4.4] Add k8s version options for TKE
  lib/shared/addon/components/cluster-driver/driver-tencenttke/component.js
Labels: status/ready-for-review

#4014 [2.4.4] Fix project switch issue on mobile
  app/components/page-header-project/component.js
Labels: status/ready-for-merge

#4015 [Master] Fix project switch issue on mobile
  app/components/page-header-project/component.js
Labels: status/ready-for-merge

#4016 [2.4] Use external UI for Aliyun ACK cluster
  app/models/cluster.js
  app/styles/abstracts/_mixins.scss
  app/styles/pages/_host.scss
  lib/global-admin/addon/clusters/new/select/controller.js
  lib/shared/addon/components/cluster-driver/driver-aliyunkcs/component.js
  lib/shared/addon/components/cluster-driver/driver-aliyunkcs/template.hbs
  lib/shared/addon/components/cru-cluster/component.js
  lib/shared/addon/utils/constants.js
  lib/shared/app/components/cluster-driver/driver-aliyunkcs/component.js
  public/assets/images/providers/aliyun.svg
  translations/de-de.yaml
  translations/en-us.yaml
  translations/ja-jp.yaml
  translations/nl-nl.yaml
  translations/pt-br.yaml
  translations/ru-ru.yaml
  translations/tr-tr.yaml
  translations/uk-ua.yaml
  translations/zh-hans.yaml
  translations/zh-hant-tw.yaml
Labels: status/ready-for-merge

#4017 [Master] Use external UI for Aliyun ACK cluster
  app/models/cluster.js
  app/styles/abstracts/_mixins.scss
  app/styles/pages/_host.scss
  lib/global-admin/addon/clusters/new/select/controller.js
  lib/shared/addon/components/cluster-driver/driver-aliyunkcs/component.js
  lib/shared/addon/components/cluster-driver/driver-aliyunkcs/template.hbs
  lib/shared/addon/components/cru-cluster/component.js
  lib/shared/addon/utils/constants.js
  lib/shared/app/components/cluster-driver/driver-aliyunkcs/component.js
  public/assets/images/providers/aliyun.svg
  translations/de-de.yaml
  translations/en-us.yaml
  translations/ja-jp.yaml
  translations/nl-nl.yaml
  translations/pt-br.yaml
  translations/ru-ru.yaml
  translations/tr-tr.yaml
  translations/uk-ua.yaml
  translations/zh-hans.yaml
  translations/zh-hant-tw.yaml
Labels: status/ready-for-merge
